DROP TABLE IF EXISTS SALES;
  
CREATE TABLE SALES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  customerId VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  salesDate DATE NOT NULL,
  salesAmount DOUBLE NOT NULL
);


